#! /bin/sh

# change caps lock to ctrl
setxkbmap -layout us -option ctrl:nocaps

pgrep -x sxhkd > /dev/null || sxhkd &
#feh --randomize --bg-fill ~/Pictures/bg/wallhaven-pk6y2p.png
feh --randomize --bg-fill ~/Pictures/Wallpapers/wallhaven-z81ovo.png
pgrep -x polybar > /dev/null || ~/.config/polybar/launch.sh &
pgrep -x fcitx5 > /dev/null || fcitx5 &
#pgrep -x clash > /dev/null || /opt/clash/clash &

bspc monitor -d Coding Web Document Media

bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
